name: 'Patch ReKernel for Kernel.'

runs:
  using: 'composite'
  steps:
      - name: Patch ReKernel
        if: env.REKERNEL_ENABLE == 'true'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/device_kernel/
          cp /tmp/Patches/Rekernel/rekernel_extra.patch ./
          patch -p1 < rekernel_extra.patch || true
          rm -f rekernel_extra.patch

          grep -q "rekernel" drivers/Makefile || printf "\nobj-\$(CONFIG_REKERNEL) += rekernel/\n" >> drivers/Makefile
          grep -q "source \"drivers/rekernel/Kconfig\"" drivers/Kconfig || sed -i "/endmenu/i\source \"drivers/rekernel/Kconfig\"" drivers/Kconfig

          echo "CONFIG_REKERNEL=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_REKERNEL_NETWORK=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}

          echo "[+] Patched Re:Kernel for your kernel successfully."
